#!/usr/bin/env bash
# 정본(.ruler/*.md)과 생성물(RULER_CLAUDE.md·AGENTS.md)의 내용 일치를 검사하는 읽기 전용 스크립트.
#
# 성격: 읽기 전용(Ruler 미실행) — 에이전트·CI 가 언제든 실행 가능하다. apply/revert 를 하지 않으므로
#       CLAUDE.md §0 위험 작업·에이전트 실쓰기 금지와 무관하다.
# 용도: `.ruler/` 를 수정하고 사람이 apply 를 안 했거나, 생성물을 직접 손댄 경우의 불일치를 잡는다.
# 전제: 버전 고정(@intellectronica/ruler@0.3.44). 버전 변경 시 Ruler 의 연결 형식(주석·구분)이
#       바뀔 수 있으므로 normalize 규칙 재검증이 필요하다(PLAN_RULER_MIGRATION §6).
#
# 종료코드: 0 일치 / 1 불일치 / 2 생성물 부재(사람 apply 필요)

set -u

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

RULER_DIR=".ruler"
GEN_CLAUDE="RULER_CLAUDE.md"
GEN_CODEX="AGENTS.md"

# 생성물 부재 시 Phase 2(사람 apply) 필요 안내 후 종료(불일치와 구분되는 exit 2)
missing=0
for f in "$GEN_CLAUDE" "$GEN_CODEX"; do
  if [ ! -f "$f" ]; then
    echo "check-sync: 생성물 $f 부재 — 사람이 'ruler apply' 로 생성해야 검사 가능하다(PLAN §3.5)."
    missing=1
  fi
done
[ "$missing" -eq 1 ] && exit 2

# normalize: 비교를 위해 양쪽 본문에서 Ruler 삽입 주석 행과 빈 줄·행말 공백을 제거한다.
#   - `<!-- Source: .ruler/<파일> -->` : Ruler 가 각 조각 앞에 붙이는 출처 주석(두 생성물 공통).
#   - `<!-- Generated by Ruler -->`    : AGENTS.md 헤더(이 파일에만 존재 — "있으면 제거").
#   - 빈 줄 제거로 파일 간 구분(빈 줄) 방식 차이에 무관하게 내용만 대조한다([A-2] 파일별 규칙 통합).
normalize() {
  grep -v -e '^<!-- Source: .*\.md -->$' -e '^<!-- Generated by Ruler -->$' \
    | sed 's/[[:space:]]*$//' \
    | grep -v '^[[:space:]]*$'
}

# 정본 본문 = .ruler/*.md 를 파일명 순(00→10→20→30, Ruler 이어붙이기 순과 동일)으로 연결 후 normalize.
canon_src="$(cat $(ls "$RULER_DIR"/*.md | sort) | normalize)"

rc=0
for gen in "$GEN_CLAUDE" "$GEN_CODEX"; do
  gen_body="$(normalize < "$gen")"
  if [ "$gen_body" = "$canon_src" ]; then
    echo "check-sync: $gen 정본 일치 (OK)"
  else
    echo "check-sync: $gen 정본 불일치 — .ruler/ 수정 후 사람 apply 재실행 필요 (FAIL)"
    diff <(printf '%s\n' "$canon_src") <(printf '%s\n' "$gen_body") | head -40
    rc=1
  fi
done

exit $rc
